node {
  name = "csms-sandbox@127.0.0.1"
  cookie = "csms-sandbox-secret-cookie"
  data_dir = "/opt/emqx/data"
}

listeners.tcp.default {
  bind = "0.0.0.0:1883"
  max_connections = 1024000
}

dashboard {
  listeners.http {
    bind = "0.0.0.0:18083"
  }
}

log {
  console {
    level = warning
  }
}

authentication = [
  {
    mechanism = password_based
    backend = http
    method = post
    url = "http://nginx/internal/mqtt/auth"
    headers {
      "Content-Type" = "application/json"
    }
    body {
      username = "${username}"
      password = "${password}"
      clientid = "${clientid}"
    }
    connect_timeout = "5s"
    request_timeout = "5s"
    pool_size = 4
  }
]

authorization {
  sources = [
    {
      type = http
      enable = true
      method = post
      url = "http://nginx/internal/mqtt/acl"
      headers {
        "Content-Type" = "application/json"
      }
      body {
        username = "${username}"
        topic = "${topic}"
        action = "${action}"
      }
      connect_timeout = "5s"
      request_timeout = "5s"
      pool_size = 4
    }
  ]
  no_match = deny
  deny_action = disconnect
}
listeners.ssl.default {
  bind = "0.0.0.0:8883"
  ssl_options {
    certfile = "/opt/emqx/etc/certs/fullchain.pem"
    keyfile = "/opt/emqx/etc/certs/privkey.pem"
    verify = verify_none
  }
  max_connections = 1024000
}
